version: "3.3"
services:
  web:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://docker.for.mac.localhost:6379
      - CELERY_BACKEND=redis://127.0.0.1:6379
      - REDIS_HOST=docker.for.mac.localhost
      - REDIS_PORT=6379
      - POSTGRES_NAME=stockdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=stocktracker
    networks:
      - app_network
    restart: on-failure
    links:
      - redis
    depends_on:
      - redis
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stockdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=stocktracker
    networks:
      - app_network

  celery:
    build: .
    command: sh -c "celery -A stocktracker.celery worker --pool=solo -l INFO"
    volumes:
      - .:/code
    depends_on:
      - redis
    links:
      - redis
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://docker.for.mac.localhost:6379
      - CELERY_BACKEND=redis://127.0.0.1:6379
      - REDIS_HOST=docker.for.mac.localhost
      - REDIS_PORT=6379
      - POSTGRES_NAME=stockdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=stocktracker
    networks:
      - app_network
  
  celerybeat:
    build: .
    command: sh -c "celery -A stocktracker.celery beat -l INFO"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    links:
      - redis
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://docker.for.mac.localhost:6379
      - CELERY_BACKEND=redis://127.0.0.1:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_NAME=stockdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=stocktracker
    networks:
      - app_network

  redis:
    image: redis:5.0.9-alpine
    ports:
      - 6379:6379

networks:
  app_network:

volumes:
  app_db: